"""Reproduce the fixed SDR GLSL port from the pinned, unmodified OpenDRT source.

No network needed. Standard look, linear Rec.709 input, Rec.709/D65 100 nit
output, bright surround (the upstream sRGB display preset), linear output.
The final shader owns sRGB encoding; applying upstream's 2.2 power as well
would encode twice.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'third_party/opendrt/OpenDRT.dctl'
DEST = ROOT / 'src/pack/shaders/lib/opendrt.glsl'
COMMIT = 'af683323e2a8a63501f02c0a724ec538e3228ad0'
s = SOURCE.read_text(encoding='utf-8')

def function(name):
    start = re.search(r'__DEVICE__ \w+ ' + name + r'\(', s).start()
    brace = s.index('{', start)
    depth, end = 1, brace + 1
    while depth:
        depth += (s[end] == '{') - (s[end] == '}')
        end += 1
    return s[start:end]

helpers = ['sdivf', 'sdivf3f', 'spowf', 'hypotf2', 'hypotf3',
           'compress_hyperbolic_power', 'compress_toe_quadratic', 'softplus',
           'gauss_window', 'opponent', 'hue_offset']
text = '\n\n'.join(function(name) for name in helpers)
text += '\nfloat odt_remainder(float a,float b) { return a-b*trunc(a/b); }\n'
# Matrix vectors in DCTL are rows. Keep row dot products explicitly.
for name in ['rec709_to_xyz', 'xyz_to_p3d65', 'p3d65_to_xyz', 'xyz_to_rec709']:
    line = re.search(r'^#define matrix_' + name + r' (.*)$', s, re.M)[1]
    rows = re.findall(r'make_float3\(([^)]+)\)', line)
    text += '\nvec3 odt_' + name + '(vec3 v) { return vec3(' + ','.join('dot(vec3(' + r + '),v)' for r in rows) + '); }\n'

standard = re.search(r'if \(look_preset==0\) \{ // Standard\s*([^}]+)', s)[1]
params = dict(re.findall(r'(\w+)\s*=\s*([^,;]+)', standard))
params.update(tn_Lp='100.0', tn_Lg='10.0', tn_gb='0.13', pt_hdr='0.5', tn_su='2', eotf='0')
core = s[s.index('  const float ts_x1 ='):s.index('  if (crv_enable == 1) {\n    crv_tsn *= ts_m2;')]
# Drop disabled branches, not arithmetic, from the Standard preset.
for condition in ['crv_enable == 1', 'tn_lcon_enable', 'tn_hcon_enable']:
    pattern = re.compile(r'\s*if \(' + re.escape(condition) + r'\)\s*')
    while m := pattern.search(core):
        end = m.end()
        if core[end] == '{':
            depth, end = 1, end + 1
            while depth:
                depth += (core[end] == '{') - (core[end] == '}')
                end += 1
        else:
            end = core.index(';', end) + 1
        core = core[:m.start()] + '\n' + core[end:]
core = core.replace('  float crv_tsn_const = 0.0f;', '')
core = core.replace('rgb = vdot(in_to_xyz, rgb);', 'rgb = odt_rec709_to_xyz(rgb);')
core = core.replace('rgb = vdot(matrix_xyz_to_p3d65, rgb);', 'rgb = odt_xyz_to_p3d65(rgb);')
core = core.replace('rgb = display_gamut_whitepoint(rgb, tsn_const, cwp_lm, display_gamut, cwp);',
                    'rgb = odt_xyz_to_rec709(odt_p3d65_to_xyz(rgb));')
core = re.sub(r'if \((\w+_enable)\)', r'if (\1 == 1)', core)
core = core.replace('(float)tn_su', 'float(tn_su)')
used = {name:value for name,value in params.items() if re.search(r'\b'+name+r'\b', core)}
constants = '\n'.join('  const '+('int' if re.fullmatch(r'\d+', value) else 'float')+' '+name+' = '+value+';' for name,value in used.items())
text += '\nvec3 openDrtDisplay(vec3 rgb) {\n'+constants+'\n'+core+'\n  return clamp(rgb*tsn,0.0,1.0);\n}\n'
for old,new in {'__DEVICE__ ':'', 'float3':'vec3', 'float2':'vec2', 'make_vec3':'vec3', 'make_vec2':'vec2',
                '_powf':'pow', '_sqrtf':'sqrt', '_fmaxf':'max', '_expf':'exp', '_logf':'log', '_log2f':'log2',
                '_fminf':'min', '_atan2f':'atan', '_fmod':'odt_remainder', 'SQRT3':'1.73205080756887729353',
                'PI':'3.14159265358979323846'}.items():
    text = text.replace(old,new)
for name in helpers:
    text = re.sub(r'\b'+name+r'\b', 'odt_'+name, text)
text = re.sub(r'\b(\d+(?:\.\d*)?(?:e[+-]?\d+)?)f\b',r'\1',text,flags=re.I)
text = text.replace('float odt_remainder(float a,float b) { return a-b*trunc(a/b); }', '')
text = 'float odt_remainder(float a,float b) { return a-b*trunc(a/b); }\n'+text
header = f'''// SPDX-License-Identifier: GPL-3.0-only
// OpenDRT v1.1.0, written by Jed Smith. GLSL specialization for Vulkanite.
// https://github.com/jedypod/open-display-transform/tree/{COMMIT}
// Changes: fixed Standard look, SDR 100 nit Rec.709 D65, bright surround,
// linear Rec.709 input and linear display output; disabled branches removed.
// Generated by components/foundation_pack/tools/ImportOpenDrt.py. License: licenses/OpenDRT-GPL-3.0.txt.
// This is a display transform, never part of PT radiance or RR input.
#ifndef FOUNDATION_OPENDRT_GLSL
#define FOUNDATION_OPENDRT_GLSL
'''
DEST.write_text(header+text+'\n#endif\n',encoding='utf-8',newline='\n')
print(f'Generated {DEST} ({len(text.splitlines())} lines)')
