mod_version=0.0.4-pre-alpha+26.3
mod_id=vulkanite
mod_name=Vulkanite
mod_group=me.cortex.vulkanite
mod_side=client
mod_authors=Cortex
mod_license=LGPL-3.0-only
mod_description=A minecraft mod that brings hardware accelerated raytracing and other vulkan features to minecraft java edition

org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.workers.max=2
