screen=VIEW_MODE SAMPLES_PER_PIXEL MAX_BOUNCES SHARC_ENABLED SHARC_CAPACITY_POWER SHARC_UPDATE_PERIOD RECONSTRUCTION_MODE RECONSTRUCTION_QUALITY AUTO_EXPOSURE EXPOSURE_EV
sliders=SAMPLES_PER_PIXEL MAX_BOUNCES SHARC_UPDATE_PERIOD
clouds=off
oldLighting=false
separateAo=true
size.buffer.colortex8=1 1
