screen=SAMPLES_PER_PIXEL MAX_BOUNCES [EXPOSURE] TONE_MAPPING
sliders=SAMPLES_PER_PIXEL MAX_BOUNCES
clouds=off
oldLighting=false
separateAo=true
iris.features.required=SSBO
shadow.enabled=true
shadowTerrain=false
shadowTranslucent=false
shadowEntities=true
size.buffer.colortex8=1 1
bufferObject.12=512

screen.EXPOSURE=AUTO_EXPOSURE EXPOSURE_EV EXPOSURE_METERING EXPOSURE_MIN_EV EXPOSURE_MAX_EV EXPOSURE_NIGHT_EV EXPOSURE_BRIGHT_SPEED EXPOSURE_DARK_SPEED EXPOSURE_LOW_PERCENT EXPOSURE_HIGH_PERCENT EXPOSURE_HIGHLIGHTS
