// SPDX-License-Identifier: GPL-3.0-only
// OpenDRT v1.1.0, written by Jed Smith. GLSL specialization for Vulkanite.
// https://github.com/jedypod/open-display-transform/tree/af683323e2a8a63501f02c0a724ec538e3228ad0
// Changes: fixed Standard look, SDR 100 nit Rec.709 D65, bright surround,
// linear Rec.709 input and linear display output; disabled branches removed.
// Generated by tools/ImportOpenDrt.py. License: licenses/OpenDRT-GPL-3.0.txt.
// This is a display transform, never part of PT radiance or RR input.
#ifndef FOUNDATION_OPENDRT_GLSL
#define FOUNDATION_OPENDRT_GLSL
float odt_remainder(float a,float b) { return a-b*trunc(a/b); }
float odt_sdivf(float a, float b) {
  if (b == 0.0) return 0.0;
  else return a/b;
}

vec3 odt_sdivf3f(vec3 a, float b) {
  return vec3(odt_sdivf(a.x, b), odt_sdivf(a.y, b), odt_sdivf(a.z, b));
}

float odt_spowf(float a, float b) {
  if (a <= 0.0) return a;
  else return pow(a, b);
}

float odt_hypotf2(vec2 v) { return sqrt(max(0.0, v.x*v.x + v.y*v.y)); }

float odt_hypotf3(vec3 v) { return sqrt(max(0.0, v.x*v.x + v.y*v.y + v.z*v.z)); }

float odt_compress_hyperbolic_power(float x, float s, float p) {
  // Simple hyperbolic compression function https://www.desmos.com/calculator/ofwtcmzc3w
  return odt_spowf(x/(x + s), p);
}

float odt_compress_toe_quadratic(float x, float toe, int inv) {
  // Quadratic toe compress function https://www.desmos.com/calculator/skk8ahmnws
  if (toe == 0.0) return x;
  if (inv == 0) {
    return odt_spowf(x, 2.0)/(x + toe);
  } else {
    return (x + sqrt(x*(4.0*toe + x)))/2.0;
  }
}

float odt_softplus(float x, float s) {
  // Softplus unconstrained
  // https://www.desmos.com/calculator/mr9rmujsmn
  if (x > 10.0*s || s < 1e-4) return x;
  return s*log(max(0.0, 1.0 + exp(x/s)));
}

float odt_gauss_window(float x, float w) {
  // Simple gaussian window https://www.desmos.com/calculator/vhr9hstlyk
  return exp(-x*x/w);
}

vec2 odt_opponent(vec3 rgb) {
  // Simple Cyan-Yellow / Green-Magenta odt_opponent space for calculating smooth achromatic distance and hue angles
  return vec2(rgb.x - rgb.z, rgb.y - (rgb.x + rgb.z)/2.0);
}

float odt_hue_offset(float h, float o) {
  // Offset hue maintaining 0-2*pi range with modulo
  return odt_remainder(h - o + 3.14159265358979323846, 2.0*3.14159265358979323846) - 3.14159265358979323846;
}


vec3 odt_rec709_to_xyz(vec3 v) { return vec3(dot(vec3(0.412390799265959229, 0.357584339383878125, 0.180480788401834347),v),dot(vec3(0.212639005871510217, 0.71516867876775625, 0.0721923153607337414),v),dot(vec3(0.0193308187155918181, 0.119194779794626018, 0.950532152249661033),v)); }

vec3 odt_xyz_to_p3d65(vec3 v) { return vec3(dot(vec3(2.49349691194142542, -0.93138361791912383, -0.402710784450716841),v),dot(vec3(-0.829488969561574696, 1.76266406031834655, 0.0236246858419435941),v),dot(vec3(0.0358458302437844531, -0.0761723892680418041, 0.956884524007687309),v)); }

vec3 odt_p3d65_to_xyz(vec3 v) { return vec3(dot(vec3(0.486570948648216151, 0.265667693169093, 0.198217285234362467),v),dot(vec3(0.228974564069748754, 0.691738521836506193, 0.079286914093744984),v),dot(vec3(-4.00000000000000029e-17, 0.0451133818589026167, 1.04394436890097575),v)); }

vec3 odt_xyz_to_rec709(vec3 v) { return vec3(dot(vec3(3.24096994190452348, -1.53738317757009435, -0.498610760293003552),v),dot(vec3(-0.969243636280879506, 1.87596750150771996, 0.0415550574071755843),v),dot(vec3(0.0556300796969936354, -0.20397695888897649, 1.05697151424287816),v)); }

vec3 openDrtDisplay(vec3 rgb) {
  const float tn_con = 1.66;
  const float tn_sh = 0.5;
  const float tn_toe = 0.003;
  const float tn_off = 0.005;
  const float rs_sa = 0.35;
  const float rs_rw = 0.25;
  const float rs_bw = 0.55;
  const float pt_lml = 0.25;
  const float pt_lml_r = 0.5;
  const float pt_lml_g = 0.0;
  const float pt_lml_b = 0.1;
  const float pt_lmh = 0.25;
  const float pt_lmh_r = 0.5;
  const float pt_lmh_b = 0.0;
  const int ptl_enable = 1;
  const float ptl_c = 0.06;
  const float ptl_m = 0.08;
  const float ptl_y = 0.06;
  const int ptm_enable = 1;
  const float ptm_low = 0.4;
  const float ptm_low_rng = 0.25;
  const float ptm_low_st = 0.5;
  const float ptm_high = -0.8;
  const float ptm_high_rng = 0.35;
  const float ptm_high_st = 0.4;
  const int brl_enable = 1;
  const float brl = 0.0;
  const float brl_r = -2.5;
  const float brl_g = -1.5;
  const float brl_b = -1.5;
  const float brl_rng = 0.5;
  const float brl_st = 0.35;
  const int brlp_enable = 1;
  const float brlp = -0.5;
  const float brlp_r = -1.25;
  const float brlp_g = -1.25;
  const float brlp_b = -0.25;
  const int hc_enable = 1;
  const float hc_r = 1.0;
  const float hc_r_rng = 0.3;
  const int hs_rgb_enable = 1;
  const float hs_r = 0.6;
  const float hs_r_rng = 0.6;
  const float hs_g = 0.35;
  const float hs_g_rng = 1.0;
  const float hs_b = 0.66;
  const float hs_b_rng = 1.0;
  const int hs_cmy_enable = 1;
  const float hs_c = 0.25;
  const float hs_c_rng = 1.0;
  const float hs_m = 0.0;
  const float hs_m_rng = 1.0;
  const float hs_y = 0.0;
  const float hs_y_rng = 1.0;
  const float tn_Lp = 100.0;
  const float tn_Lg = 10.0;
  const float tn_gb = 0.13;
  const float pt_hdr = 0.5;
  const int tn_su = 2;
  const int eotf = 0;
  const float ts_x1 = pow(2.0, 6.0*tn_sh + 4.0);
  const float ts_y1 = tn_Lp/100.0;
  const float ts_x0 = 0.18 + tn_off;
  const float ts_y0 = tn_Lg/100.0*(1.0 + tn_gb*log2(ts_y1));
  const float ts_s0 = odt_compress_toe_quadratic(ts_y0, tn_toe, 1);
  const float ts_p = tn_con/(1.0 + float(tn_su)*0.05); // unconstrained surround compensation
  const float ts_s10 = ts_x0*(pow(ts_s0, -1.0/tn_con) - 1.0);
  const float ts_m1 = ts_y1/pow(ts_x1/(ts_x1 + ts_s10), tn_con);
  const float ts_m2 = odt_compress_toe_quadratic(ts_m1, tn_toe, 1);
  const float ts_s = ts_x0*(pow(ts_s0/ts_m2, -1.0/tn_con) - 1.0);
  const float ts_dsc = eotf==4 ? 0.01 : eotf==5 ? 0.1 : 100.0/tn_Lp;

  // Lerp from pt_cmp at 100 nits to pt_cmp_hdr at 1000 nits
  const float pt_cmp_Lf = pt_hdr*min(1.0, (tn_Lp - 100.0)/900.0);
  // Approximate scene-linear scale at Lp=100 nits
  const float s_Lp100 = ts_x0*(pow((tn_Lg/100.0), -1.0/tn_con) - 1.0);
  const float ts_s1 = ts_s*pt_cmp_Lf + s_Lp100*(1.0 - pt_cmp_Lf);


  // Convert from input gamut into P3-D65
  rgb = odt_rec709_to_xyz(rgb);
  rgb = odt_xyz_to_p3d65(rgb);


  // Rendering Space: "Desaturate" to control scale of the color volume in the rgb ratios.
  // Controlled by rs_sa (saturation) and red and blue weights (rs_rw and rs_bw)
  vec3 rs_w = vec3(rs_rw, 1.0 - rs_rw - rs_bw, rs_bw);
  float sat_L = rgb.x*rs_w.x + rgb.y*rs_w.y + rgb.z*rs_w.z;
  rgb = sat_L*rs_sa + rgb*(1.0 - rs_sa);


  // Offset
  rgb += tn_off;



  // Tonescale Norm
  float tsn = odt_hypotf3(rgb)/1.73205080756887729353;

  // RGB Ratios
  rgb = odt_sdivf3f(rgb, tsn);
  
  vec2 opp = odt_opponent(rgb);
  float ach_d = odt_hypotf2(opp)/2.0;
  
  // Smooth ach_d, normalized so 1.0 doesn't change https://www.desmos.com/calculator/ozjg09hzef
  ach_d = (1.25)*odt_compress_toe_quadratic(ach_d, 0.25, 0);

  // Hue angle, rotated so that red = 0.0
  float hue = odt_remainder(atan(opp.x, opp.y) + 3.14159265358979323846 + 1.10714931, 2.0*3.14159265358979323846);

  // RGB Hue Angles
  // Wider than CMY by default. R towards M, G towards Y, B towards C
  vec3 ha_rgb = vec3(
    odt_gauss_window(odt_hue_offset(hue, 0.1), 0.66),
    odt_gauss_window(odt_hue_offset(hue, 4.3), 0.66),
    odt_gauss_window(odt_hue_offset(hue, 2.3), 0.66));
    
  // RGB Hue Angles for hue shift: red shifted more orange
  vec3 ha_rgb_hs = vec3(
    odt_gauss_window(odt_hue_offset(hue, -0.4), 0.66),
    ha_rgb.y,
    odt_gauss_window(odt_hue_offset(hue, 2.5), 0.66));
  
  // CMY Hue Angles
  // Exact alignment to Cyan/Magenta/Yellow secondaries would be 3.14159265358979323846, 3.14159265358979323846/3 and -3.14159265358979323846/3, but
  // we customize these a bit for creative purposes: M towards B, Y towards G, C towards G
  vec3 ha_cmy = vec3(
    odt_gauss_window(odt_hue_offset(hue, 3.3), 0.5),
    odt_gauss_window(odt_hue_offset(hue, 1.3), 0.5),
    odt_gauss_window(odt_hue_offset(hue, -1.15), 0.5));


  // Brilliance
  if (brl_enable == 1) {
    float brl_tsf = pow(tsn/(tsn + 1.0), 1.0 - brl_rng);
    float brl_exf = (brl + brl_r*ha_rgb.x + brl_g*ha_rgb.y + brl_b*ha_rgb.z)*pow(ach_d, 1.0/brl_st);
    float brl_ex = pow(2.0, brl_exf*(brl_exf < 0.0 ? brl_tsf : 1.0 - brl_tsf));
    tsn *= brl_ex;
  }

  // Contrast Low


  // Contrast High


  // Hyperbolic Compression
  float tsn_pt = odt_compress_hyperbolic_power(tsn, ts_s1, ts_p);
  float tsn_const = odt_compress_hyperbolic_power(tsn, s_Lp100, ts_p);
  tsn = odt_compress_hyperbolic_power(tsn, ts_s, ts_p);
  





  /***************************************************
    Hue Contrast R
  --------------------------------------------------*/
  if (hc_enable == 1) {
    float hc_ts = 1.0 - tsn_const;
    // Limit high purity on bottom end and low purity on top end by ach_d.
    // This helps reduce artifacts and over-saturation.
    float hc_c = hc_ts*(1.0 - ach_d) + ach_d*(1.0 - hc_ts);
    hc_c *= ach_d*ha_rgb.x;
    hc_ts = pow(hc_ts, 1.0/hc_r_rng);
    // Bias contrast based on tonescale using Lift/Mult: https://www.desmos.com/calculator/gzbgov62hl
    float hc_f = hc_r*(hc_c - 2.0*hc_c*hc_ts) + 1.0;
    rgb = vec3(rgb.x, rgb.y*hc_f, rgb.z*hc_f);
  }



  /***************************************************
    Hue Shift
  --------------------------------------------------*/
  // Hue Shift RGB by purity compress tonescale, shifting more as intensity increases
  if (hs_rgb_enable == 1) {
    vec3 hs_rgb = vec3(
      ha_rgb_hs.x*ach_d*pow(tsn_pt, 1.0/hs_r_rng),
      ha_rgb_hs.y*ach_d*pow(tsn_pt, 1.0/hs_g_rng),
      ha_rgb_hs.z*ach_d*pow(tsn_pt, 1.0/hs_b_rng));
    vec3 hsf = vec3(hs_rgb.x*hs_r, hs_rgb.y*-hs_g, hs_rgb.z*-hs_b);
    hsf = vec3(hsf.z - hsf.y, hsf.x - hsf.z, hsf.y - hsf.x);
    rgb += hsf;
  }

  // Hue Shift CMY by tonescale, shifting less as intensity increases
  if (hs_cmy_enable == 1) {
    float tsn_pt_compl = 1.0 - tsn_pt;
    vec3 hs_cmy = vec3(
      ha_cmy.x*ach_d*pow(tsn_pt_compl, 1.0/hs_c_rng),
      ha_cmy.y*ach_d*pow(tsn_pt_compl, 1.0/hs_m_rng),
      ha_cmy.z*ach_d*pow(tsn_pt_compl, 1.0/hs_y_rng));
    vec3 hsf = vec3(hs_cmy.x*-hs_c, hs_cmy.y*hs_m, hs_cmy.z*hs_y);
    hsf = vec3(hsf.z - hsf.y, hsf.x - hsf.z, hsf.y - hsf.x);
    rgb += hsf;
  }



  /***************************************************
    Purity Compression
      https://www.desmos.com/calculator/adtzkjofgn
  --------------------------------------------------*/
  // Purity Limit Low
  float pt_lml_p = 1.0 + 4.0*(1.0 - tsn_pt)*(pt_lml + pt_lml_r*ha_rgb_hs.x + pt_lml_g*ha_rgb_hs.y + pt_lml_b*ha_rgb_hs.z);
  float ptf = 1.0 - pow(tsn_pt, pt_lml_p);
  
  // Purity Limit High
  float pt_lmh_p = (1.0 - ach_d*(pt_lmh_r*ha_rgb_hs.x + pt_lmh_b*ha_rgb_hs.z))*(1.0 - pt_lmh*ach_d);
  ptf = pow(ptf, pt_lmh_p);

  
  /***************************************************
    Mid-Range Purity
      This boosts mid-range purity on the low end
      and reduces mid-range purity on the high end
  --------------------------------------------------*/
  if (ptm_enable == 1) {
    float ptm_low_f;
    if (ptm_low_st == 0.0 || ptm_low_rng == 0.0) ptm_low_f = 1.0;
    else ptm_low_f = 1.0 + ptm_low*exp(-2.0*ach_d*ach_d/ptm_low_st)*pow(1.0 - tsn_const, 1.0/ptm_low_rng);
    float ptm_high_f;
    if (ptm_high_st == 0.0 || ptm_high_rng == 0.0) ptm_high_f = 1.0;
    else ptm_high_f = 1.0 + ptm_high*exp(-2.0*ach_d*ach_d/ptm_high_st)*pow(tsn_pt, 1.0/(4.0*ptm_high_rng));
    ptf *= ptm_low_f*ptm_high_f;
  }

  // Lerp to peak achromatic by ptf in rgb ratios
  rgb = rgb*ptf + 1.0 - ptf;

  // Inverse Rendering Space
  sat_L = rgb.x*rs_w.x + rgb.y*rs_w.y + rgb.z*rs_w.z;
  rgb = (sat_L*rs_sa - rgb)/(rs_sa - 1.0);

  // Convert to final display gamut and set whitepoint
  rgb = odt_xyz_to_rec709(odt_p3d65_to_xyz(rgb));
  
  // Post Brilliance
  if (brlp_enable == 1) {
    vec2 brlp_opp = odt_opponent(rgb);
    float brlp_ach_d = odt_hypotf2(brlp_opp)/4.0;
    // brlp_ach_d = 1.0 - odt_gauss_window(brlp_ach_d, 8.0);
    brlp_ach_d = 1.1*(brlp_ach_d*brlp_ach_d/(brlp_ach_d + 0.1));
    vec3 brlp_ha_rgb = ach_d*ha_rgb;
    float brlp_m = brlp + brlp_r*brlp_ha_rgb.x + brlp_g*brlp_ha_rgb.y + brlp_b*brlp_ha_rgb.z;
    float brlp_ex = pow(2.0, brlp_m*brlp_ach_d*tsn);
    rgb *= brlp_ex;
  }

  // Purity Compress Low
  if (ptl_enable == 1) rgb = vec3(odt_softplus(rgb.x, ptl_c), odt_softplus(rgb.y, ptl_m), odt_softplus(rgb.z, ptl_y));
 
  // Final tonescale adjustments
  tsn *= ts_m2; // scale for inverse toe
  tsn = odt_compress_toe_quadratic(tsn, tn_toe, 0);
  tsn *= ts_dsc; // scale for display encoding
  

  return clamp(rgb*tsn,0.0,1.0);
}

#endif
